# Generated by Django 3.1 on 2020-08-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enertrack", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installedcapacity",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enertrack.country"
            ),
        ),
    ]
