# Generated by Django 3.1 on 2020-09-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enertrack", "0005_dates_forecast_again"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(help_text="expressed in kW")),
                ("start_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField()),
                (
                    "production_type",
                    models.CharField(
                        choices=[
                            ("AGGREGATED_FRANCE", "aggregated_france"),
                            ("WIND", "wind"),
                            ("AGGREGATED_CPC", "aggregated_cpc"),
                            ("SOLAR", "solar"),
                            ("MDSE", "mdse"),
                        ],
                        default="SOLAR",
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enertrack.country",
                    ),
                ),
            ],
        ),
    ]
