# Generated by Django 3.1 on 2020-09-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enertrack", "0006_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installedcapacity",
            name="production_type",
            field=models.CharField(
                choices=[
                    ("FOSSIL_GAS", "gas"),
                    ("FOSSIL_HARD_COAL", "coal"),
                    ("HYDRO_PUMPED_STORAGE", "hydro_pumped_storage"),
                    ("NUCLEAR", "nuclear"),
                    ("SOLAR", "solar"),
                    ("WIND_OFFSHORE", "wind_offshore"),
                    ("WIND_ONSHORE", "wind_onshore"),
                    ("WIND", "wind"),
                ],
                default="SOLAR",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="measure",
            name="production_type",
            field=models.CharField(
                choices=[
                    ("FOSSIL_GAS", "gas"),
                    ("FOSSIL_HARD_COAL", "coal"),
                    ("HYDRO_PUMPED_STORAGE", "hydro_pumped_storage"),
                    ("NUCLEAR", "nuclear"),
                    ("SOLAR", "solar"),
                    ("WIND_OFFSHORE", "wind_offshore"),
                    ("WIND_ONSHORE", "wind_onshore"),
                    ("WIND", "wind"),
                ],
                default="SOLAR",
                max_length=50,
            ),
        ),
    ]
