# Generated by Django 3.1 on 2020-08-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={"verbose_name_plural": "Countries",},
        ),
        migrations.CreateModel(
            name="InstalledCapacity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(help_text="expressed in kW")),
                ("date", models.DateField()),
                (
                    "production_type",
                    models.CharField(
                        choices=[
                            ("FOSSIL_GAS", "gas"),
                            ("FOSSIL_HARD_COAL", "coal"),
                            ("HYDRO_PUMPED_STORAGE", "hydro_pumped_storage"),
                            ("NUCLEAR", "nuclear"),
                            ("SOLAR", "solar"),
                            ("WIND_OFFSHORE", "wind_offshore"),
                            ("WIND_ONSHORE", "wind_onshore"),
                        ],
                        default="SOLAR",
                        max_length=50,
                    ),
                ),
                (
                    "country",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enertrack.country",
                    ),
                ),
            ],
            options={"verbose_name_plural": "InstalledCapacities",},
        ),
    ]
