# Generated by Django 3.1 on 2020-08-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enertrack", "0002_auto_20200826_1410"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(help_text="expressed in kW")),
                ("date", models.DateField()),
                (
                    "forecast_production_type",
                    models.CharField(
                        choices=[
                            ("AGGREGATED_FRANCE", "aggregated_france"),
                            ("WIND", "wind"),
                            ("AGGREGATED_CPC", "aggregated_cpc"),
                            ("SOLAR", "solar"),
                            ("MDSE", "mdse"),
                        ],
                        default="SOLAR",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CURRENT", "current"),
                            ("ID", "id"),
                            ("D-1", "d-1"),
                            ("D-2", "d-2"),
                            ("D-3", "d-3"),
                        ],
                        default="CURRENT",
                        max_length=7,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enertrack.country",
                    ),
                ),
            ],
        ),
    ]
