# Generated by Django 3.1 on 2020-08-27 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enertrack", "0003_forecast"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecast", old_name="date", new_name="start_date",
        ),
        migrations.AddField(
            model_name="forecast",
            name="updated_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
